import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';
import './globals.css';

import { GlobalProviders } from '@/app/_components/global-providers';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/cn';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// eslint-disable-next-line react/function-component-definition
let CacheToolbar: React.ComponentType = () => null;

if (process.env.NODE_ENV === 'development') {
  CacheToolbar = dynamic(() => import('./_components/cache-toolbar'));
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', inter.variable)}>
        <GlobalProviders>
          <CacheToolbar />
          <Toaster />
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
