import { redirect } from 'next/navigation';

import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { Separator } from '@/components/ui/separator';
import { createServerSupabaseClient } from '@/lib/utils/supabase/server';

import { AccountDropdown } from './_components/account-dropdown';
import { GlobalDialogs } from './_components/global-dialogs';
import { Navbar } from './_components/navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
  const supabase = createServerSupabaseClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect('/auth');
  }

  return (
    <>
      <GlobalDialogs />
      <ResizablePanelGroup direction="horizontal" className="h-full min-h-screen items-stretch">
        <ResizablePanel defaultSize={20} minSize={10} maxSize={30}>
          <div className="flex h-14 items-center justify-center px-2">
            <AccountDropdown user={user} />
          </div>
          <Separator />
          <Navbar />
        </ResizablePanel>
        <ResizableHandle withHandle />
        <ResizablePanel defaultSize={80}>{children}</ResizablePanel>
      </ResizablePanelGroup>
    </>
  );
}
