import { CubeIcon } from '@radix-ui/react-icons';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { Separator } from '@/components/ui/separator';

import { AccountDropdown } from './_components/account-dropdown';
import { NavItem } from './_components/nav-item';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect('/');
  }

  return (
    <ResizablePanelGroup direction="horizontal" className="h-full min-h-screen items-stretch">
      <ResizablePanel defaultSize={20} minSize={10} maxSize={30}>
        <div className="flex h-[52px] items-center justify-center px-2">
          <AccountDropdown user={user} />
        </div>
        <Separator />
        <nav className="flex flex-col gap-1 p-2">
          <NavItem href="#">
            <CubeIcon className="mr-2" /> Nav 1
          </NavItem>
          <NavItem href="#">
            <CubeIcon className="mr-2" /> Nav 2
          </NavItem>
        </nav>
      </ResizablePanel>
      <ResizableHandle withHandle />
      <ResizablePanel defaultSize={80} className="p-2">
        {children}
      </ResizablePanel>
    </ResizablePanelGroup>
  );
}
